#!/bin/sh
if [ "${1}" == "post" ]; then
  echo -n none > /sys/devices/platform/i8042/serio1/drvctl
  sleep 1
  printf "Apply patch to reload Elantech TrackPoint after suspend" | systemd-cat -t "/lib/systemd/system-sleep/trackpad"	
  echo -n reconnect > /sys/devices/platform/i8042/serio1/drvctl
fi
